on:
  push:
  workflow_dispatch:

name: Build project

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: npm - build
        run: npm run build

      - name: Compress & Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: .
          include-hidden-files: true
